[tool.poetry]
name = "fastdoc"
version = "0.1.0"
description = "A tool for creating docx documents in a fast way"
authors = ["renatormc <renatomartinsrmc@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.1.1"
PyQt5 = "^5.15.6"
docxtpl = "^0.15.2"
stringcase = "^1.2.0"
beautifulsoup4 = "^4.10.0"
inquirerpy = "^0.3.3"
Flask-WTF = "^1.0.1"
humanfriendly = "^10.0"
Bootstrap-Flask = "^2.0.2"
report-writer = {git = "https://github.com/renatormc/report_writer", branch= "master"}
Unidecode = "^1.3.4"

[tool.poetry.dev-dependencies]
PyQt5-stubs = "^5.15.2"
mypy = "^0.942"
types-Flask = "^1.1.6"
types-humanfriendly = "^9.2.6"
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
