# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fastdoc\gui_app\main_window\dialog_token\dialog_token.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogToken(object):
    def setupUi(self, DialogToken):
        DialogToken.setObjectName("DialogToken")
        DialogToken.resize(681, 268)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogToken)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(DialogToken)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.led_name = QtWidgets.QLineEdit(DialogToken)
        self.led_name.setObjectName("led_name")
        self.verticalLayout.addWidget(self.led_name)
        self.label_2 = QtWidgets.QLabel(DialogToken)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pte_token = QtWidgets.QPlainTextEdit(DialogToken)
        self.pte_token.setObjectName("pte_token")
        self.verticalLayout.addWidget(self.pte_token)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogToken)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogToken)
        QtCore.QMetaObject.connectSlotsByName(DialogToken)

    def retranslateUi(self, DialogToken):
        _translate = QtCore.QCoreApplication.translate
        DialogToken.setWindowTitle(_translate("DialogToken", "Cadastrar Token"))
        self.label.setText(_translate("DialogToken", "Nome"))
        self.label_2.setText(_translate("DialogToken", "Token"))
