"""teste

Revision ID: 102c38f51647
Revises: a09c37f3795b
Create Date: 2022-05-16 17:11:09.095544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102c38f51647'
down_revision = 'a09c37f3795b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('json_value', sa.Column('category', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('json_value', 'category')
    # ### end Alembic commands ###
