"""teste

Revision ID: a09c37f3795b
Revises: 
Create Date: 2022-04-22 16:35:49.642509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09c37f3795b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=300), nullable=True),
    sa.Column('list_name', sa.String(length=300), nullable=True),
    sa.Column('key', sa.String(length=300), nullable=True),
    sa.Column('data_str', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('json_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=300), nullable=True),
    sa.Column('data_str', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.drop_table('json_value')
    op.drop_table('item_list')
    # ### end Alembic commands ###
