# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_app/test_widget/test_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TestWidget(object):
    def setupUi(self, TestWidget):
        TestWidget.setObjectName("TestWidget")
        TestWidget.resize(400, 300)

        self.retranslateUi(TestWidget)
        QtCore.QMetaObject.connectSlotsByName(TestWidget)

    def retranslateUi(self, TestWidget):
        _translate = QtCore.QCoreApplication.translate
        TestWidget.setWindowTitle(_translate("TestWidget", "TestWidget"))
