# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_app/widgets/sobjects_by_pics/pics_organizer/pics_organizer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PicsOrganizer(object):
    def setupUi(self, PicsOrganizer):
        PicsOrganizer.setObjectName("PicsOrganizer")
        PicsOrganizer.resize(1219, 898)
        self.verticalLayout = QtWidgets.QVBoxLayout(PicsOrganizer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(PicsOrganizer)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.led_alias_pericias = QtWidgets.QLineEdit(PicsOrganizer)
        self.led_alias_pericias.setObjectName("led_alias_pericias")
        self.horizontalLayout.addWidget(self.led_alias_pericias)
        self.label_3 = QtWidgets.QLabel(PicsOrganizer)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.spb_n_objetos = QtWidgets.QSpinBox(PicsOrganizer)
        self.spb_n_objetos.setMinimumSize(QtCore.QSize(70, 0))
        self.spb_n_objetos.setObjectName("spb_n_objetos")
        self.horizontalLayout.addWidget(self.spb_n_objetos)
        self.btn_reconfig = QtWidgets.QPushButton(PicsOrganizer)
        self.btn_reconfig.setObjectName("btn_reconfig")
        self.horizontalLayout.addWidget(self.btn_reconfig)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(5, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(PicsOrganizer)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1199, 813))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lay_objects = QtWidgets.QHBoxLayout()
        self.lay_objects.setObjectName("lay_objects")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lsw_others = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.lsw_others.setDragDropOverwriteMode(False)
        self.lsw_others.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.lsw_others.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.lsw_others.setIconSize(QtCore.QSize(150, 150))
        self.lsw_others.setViewMode(QtWidgets.QListView.IconMode)
        self.lsw_others.setObjectName("lsw_others")
        self.verticalLayout_2.addWidget(self.lsw_others)
        self.lay_objects.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lay_objects.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.lay_objects)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.bbx_default = QtWidgets.QDialogButtonBox(PicsOrganizer)
        self.bbx_default.setOrientation(QtCore.Qt.Horizontal)
        self.bbx_default.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.bbx_default.setObjectName("bbx_default")
        self.verticalLayout.addWidget(self.bbx_default)

        self.retranslateUi(PicsOrganizer)
        QtCore.QMetaObject.connectSlotsByName(PicsOrganizer)

    def retranslateUi(self, PicsOrganizer):
        _translate = QtCore.QCoreApplication.translate
        PicsOrganizer.setWindowTitle(_translate("PicsOrganizer", "PicsOrganizer"))
        self.label.setText(_translate("PicsOrganizer", "Alias da perícia"))
        self.label_3.setText(_translate("PicsOrganizer", "Número de objetos"))
        self.btn_reconfig.setText(_translate("PicsOrganizer", "Reconfigurar"))
        self.label_2.setText(_translate("PicsOrganizer", "Outros"))
