# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fastdoc/gui_app/manage_models/manage_models.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManageModels(object):
    def setupUi(self, ManageModels):
        ManageModels.setObjectName("ManageModels")
        ManageModels.resize(544, 115)
        self.verticalLayout = QtWidgets.QVBoxLayout(ManageModels)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbx_model = QtWidgets.QComboBox(ManageModels)
        self.cbx_model.setObjectName("cbx_model")
        self.verticalLayout.addWidget(self.cbx_model)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_import = QtWidgets.QPushButton(ManageModels)
        self.btn_import.setMinimumSize(QtCore.QSize(100, 40))
        self.btn_import.setObjectName("btn_import")
        self.horizontalLayout.addWidget(self.btn_import)
        self.btn_export = QtWidgets.QPushButton(ManageModels)
        self.btn_export.setMinimumSize(QtCore.QSize(100, 40))
        self.btn_export.setObjectName("btn_export")
        self.horizontalLayout.addWidget(self.btn_export)
        self.btn_remove = QtWidgets.QPushButton(ManageModels)
        self.btn_remove.setMinimumSize(QtCore.QSize(100, 40))
        self.btn_remove.setObjectName("btn_remove")
        self.horizontalLayout.addWidget(self.btn_remove)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ManageModels)
        QtCore.QMetaObject.connectSlotsByName(ManageModels)

    def retranslateUi(self, ManageModels):
        _translate = QtCore.QCoreApplication.translate
        ManageModels.setWindowTitle(_translate("ManageModels", "Gerenciar modelos"))
        self.btn_import.setText(_translate("ManageModels", "Importar"))
        self.btn_export.setText(_translate("ManageModels", "Exportar"))
        self.btn_remove.setText(_translate("ManageModels", "Remover"))
