# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_app/widgets/sobjects_by_pics/pics_organizer/organizer_obj/organizer_obj.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OrganizerObj(object):
    def setupUi(self, OrganizerObj):
        OrganizerObj.setObjectName("OrganizerObj")
        OrganizerObj.resize(521, 826)
        self.verticalLayout = QtWidgets.QVBoxLayout(OrganizerObj)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_name = QtWidgets.QLabel(OrganizerObj)
        self.lbl_name.setObjectName("lbl_name")
        self.verticalLayout.addWidget(self.lbl_name)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(OrganizerObj)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cbx_type = QtWidgets.QComboBox(OrganizerObj)
        self.cbx_type.setObjectName("cbx_type")
        self.horizontalLayout.addWidget(self.cbx_type)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lsw_object = QtWidgets.QListWidget(OrganizerObj)
        self.lsw_object.setViewMode(QtWidgets.QListView.IconMode)
        self.lsw_object.setObjectName("lsw_object")
        self.verticalLayout.addWidget(self.lsw_object)

        self.retranslateUi(OrganizerObj)
        QtCore.QMetaObject.connectSlotsByName(OrganizerObj)

    def retranslateUi(self, OrganizerObj):
        _translate = QtCore.QCoreApplication.translate
        OrganizerObj.setWindowTitle(_translate("OrganizerObj", "OrganizerObj"))
        self.lbl_name.setText(_translate("OrganizerObj", "Sem nome"))
        self.label.setText(_translate("OrganizerObj", "Tipo"))
